name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        java: [ 11, 17 ]
        experimental: [false]
#        include:
#          - java: 18-ea
#            experimental: true

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4.2.0
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v4.0.1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
